prSections:
- title: All Opened PR
  filters: is:open
- title: Created
  filters: is:open author:@me
- title: To Review
  filters: is:open review-requested:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Commented
  filters: is:open commenter:@me
- title: Involved
  filters: is:open involves:@me -author:@me
- title: Tobi
  filters: owner:this-is-tobi is:open
issuesSections:
- title: All Opened Issues
  filters: is:open
- title: Created
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Commented
  filters: is:open commenter:@me
- title: Involved
  filters: is:open involves:@me -author:@me
- title: Tobi
  filters: owner:this-is-tobi is:open
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  preview:
    open: true
    width: 100
  prsLimit: 50
  prApproveComment: LGTM
  issuesLimit: 50
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal:
  - key: "shift+up"
    builtin: "pageUp"
    description: "Show top of the preview page"
  - key: "shift+down"
    builtin: "pageDown"
    description: "Show bottom of the preview page"
  issues: []
  prs:
  - key: "shift+left"
    builtin: "prevSidebarTab"
    description: "Show previous sidebar tab"
  - key: "shift+right"
    builtin: "nextSidebarTab"
    description: "Show next sidebar tab"
  - key: "n"
    command: nvim {{.RepoPath}}
    description: "Open nvim in the current directory"
  branches: []
repoPaths:
  this-is-tobi/*: ~/dev/perso/*
  IA-Generative/*: ~/dev/pro/mirai/*
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
pager:
  diff: ""
confirmQuit: true
showAuthorIcons: true
smartFilteringAtLaunch: true
